cc_library(
    name = "diseasetrackobject",
    srcs = ["diseasetrackobject.cpp"],
    hdrs = ["diseasetrackobject.h"],
    visibility = ["//visibility:public"],
    deps = [
       "@SigSlot",
    ],
)
