cc_library(
    name = "reaction",
    srcs = ["reaction.cpp"],
    hdrs = ["reaction.h"],
    visibility = ["//visibility:public"],
    deps = [
       "//diseasetrackobject:diseasetrackobject",
       "//common:defaults",
       "@cpp-base64",
       "//web:web",
    ],
)
