cc_library(
    name = "defaults",
    hdrs = glob(["defaults.h"]),
    visibility = ["//visibility:public"],
    deps = [
    ],
)

cc_library(
    name = "cluster",
    srcs = ["cluster.cpp"],
    hdrs = glob(["cluster.h"]),
    visibility = ["//visibility:public"],
    deps = [
      "@cpp-base64",
    ],
)
