cc_library(
    name = "crypto",
    srcs = ["crypto.cpp"],
    hdrs = ["crypto.h"],
    visibility = ["//visibility:public"],
    deps = [
      "@cpp-base64",    
    ],
    defines = [
    
    ],
)
