cc_library(
    name = "api",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    visibility = ["//visibility:public"],
    deps = [
       "//diseasetrackobject:diseasetrackobject",
       "//common:defaults",
       "//crypto:crypto",
       "//db:db",
       "@cpp-base64",
    ],
)
