cc_library(
    name = "web",
    srcs = ["web.cpp"],
    hdrs = ["web.h"],
    visibility = ["//visibility:public"],
    deps = [
       "//diseasetrackobject:diseasetrackobject",
       "//common:defaults",
       "@SimpleWebServer",
       "//api:api",
    ],
)
